### ISSUE TITLE
KubeSpawner support

### ISSUE THREAD

**Issue by elgalu** [ideonate/cdsdashboards#1]
Thanks for this project! I saw:

> Support for Kubernetes JupyterHub installations running KubeSpawner is in development

So maybe we can keep this issue to track the status of KubeSpawner support

**Comment by danlester** [comment]
@elgalu Thank you very much for your interest! Opening this issue is a great idea.

There are a few different configurations and use cases that I have in mind though.

Would you be kind enough to share your expertise on how you and your organization are using JupyterHub at the moment, and how you expect individual users to make use of ContainDS Dashboards? (i.e. the workflow, version control, storage etc from development to publishing a dashboard.)

Ideally we would connect on a call so I can build up a clear picture - please email dan@containds.com and we can work something out.

Anyone else visiting this issue should also get in touch! Understanding the range of use cases and configurations is really important.

**Comment by danlester** [comment]
ContainDS Dashboards version 0.0.17 includes support for Kubernetes! So you can now create a Dashboard from your notebooks or scripts and deploy directly within your JupyterHub so others can interact with a user-friendly version (e.g. Voila, Plotly Dash, Streamlit) 

The exact approach depends on your k8s, as discussed in the [setup instructions here](https://cdsdashboards.readthedocs.io/en/stable/chapters/setup/z2jh.html).

There may be nuances of your setup that need to be ironed out, so please do [get in touch](dan@containds.com) to let me know how it goes for you, or to work through it together.

I'll close this issue for now.

Thanks!
