### ISSUE TITLE
Create a JupyterLab extension to ease dashboard creation

### ISSUE THREAD

**Issue by fcollonval** [ideonate/cdsdashboards#12]
**Is your feature request related to a problem? Please describe.**

The hub pages are kind of hidden (except for the login page) for the JupyterLab single user. The creation of a dashboard from a hub page is a bit cryptic for the final user (that have no clue about the software architecture). 

**Describe the solution you'd like**

It would be nice to show the dashboard creation form from within JupyterLab - the must would be a publish button next to the voilà preview.

> If you think it is not too hard, I gladly find time next month to create a PoC. Should it be part of this project (like for voila lab preview) or a separate one on my personal account?

**Describe alternatives you've considered**
N/A

**Background context**
It is essential to understand the wider context of what you are trying to achieve from ContainDS Dashboards. Please explain your job role, and how/why your team are using the software in the first place when you encounter this need.

**Configuration**
If specific to a configuration type, include as much jupyterhub_config information as necessary - at least enough to understand which Spawner type you are using, and how your JupyterHub is deployed (e.g. The Littlest JupyterHub, or Zero to JupyterHub).

**Comment by danlester** [comment]
Thank you for the suggestion. Yes, a companion Jupyter extension is definitely something in my mind. This is for a few reasons including the use case you suggested.

I think the simplest solution to your workflow would be for a Jupyter Lab/Notebook button that just redirects to /hub/dashboards-new/?dashboard-name=<Notebook Name>&dashboard-path=<ipynb relative path>

and then a little bit of work on the cdsdashboards side would be able to pre-populate the text boxes. Maybe even better if it can detect an existing dashboard at the same relative path ipynb file, and open that for editing instead of starting a new one.

By the way, if dashboards become an important part of your workflow for many users, you might also consider changing the default landing page within JupyterHub. Some ideas [are here](https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/finetune.html). That could be important especially for the non-developers' workflow.

This is on my list anyway!

**Comment by danlester** [comment]
I have started the skeleton of this Jupyter extension here:

https://github.com/ideonate/jupyter-containds

There is no point running it at the moment - it just adds a new icon to the notebook toolbar in JupyterLab, but it doesn't really go anywhere... The cdsdashboards endpoint needs to be in place first.

Anyway, I'm linking to it from here in case anyone wants to watch the repo.

**Comment by danlester** [comment]
We now have this, requiring version 0.3.3 of cdsdashboards! Thanks @fcollonval and @adriendelsalle for completing this.
