### ISSUE TITLE
some ipywidgets are not displayed

### ISSUE THREAD

**Issue by tomnewg** [ideonate/cdsdashboards#17]
I managed to install cdsdashboards and to create new dashboards. Many thanks for creating this tool!

For some reason, some ipywidgets such as dropdown menus and radio buttons are not displayed. I also have a green bar at the top and the widgets that are displayed look a bit odd and not how voila displays them. I attached one screenshot of how the dashboard looks in voila and how it looks with cdsdashboards. Any idea why that is?

Many thanks
Tom

![image](https://user-images.githubusercontent.com/58906672/87297282-8a326900-c54b-11ea-8855-0a1f0801b9ce.png)

![image](https://user-images.githubusercontent.com/58906672/87297362-a3d3b080-c54b-11ea-9e92-de47cdfe584b.png)

**Comment by danlester** [comment]
@tomnewg Thanks for getting in touch - I'm pleased you've been able to try it out and get it working!

I think this is just down to the default Voila template being used by ContainDS Dashboards. A lot of people complain that the default Voila template isn't exciting enough, so it uses 'voila-materialstream' as the default. But this is obviously changing things in your case, in a way that isn't quite working for you.

To get back to the default Voila template, there is a [setting you can use](https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/huboptions.html#voila-template) in jupyterhub_config.py. Just try:

```
c.VariableMixin.voila_template = 'default'
```

You'll need to restart the JupyterHub, and then also recreate the dashboard (click to edit the dashboard settings from the Dashboards menu in JupyterHub, then click Save to restart).

Please let me know if this helps!

**Comment by tomnewg** [comment]
thanks Dan great it worked! Just one more thing since I installed cdsdashboard and I added cdsdashboards_config.py to the server, whenever I run "sudo tljh-config reload" it just says active and nothing else i.e. it doesn't let me write another command. However, when opening jipyterhub the tljh-config has been reloaded and everything works fine. Do you know why the sudo tljh-config reload doesn't seem to completely run through?

**Comment by danlester** [comment]
Great to hear that worked!

Regarding the TLJH reload, it's not something I've come across... It might be worth just trying to hide the cdsdashboards_config.py file temporarily to see if there is still a problem with the reload - it might be something else that changed at the install time rather than the file itself.

Either way, you might also check the [JupyterHub logs](https://tljh.jupyter.org/en/latest/troubleshooting/logs.html) to see what it says during restart.

Maybe TLJH issues will be the best place to report this ultimately, but we should see what we can understand about it first. I presume the restart ultimately seems to be successful, even if the command doesn't return?

**Comment by tomnewg** [comment]
Hi Dan,

thanks for this. The last entry in the installer.log says "2020-07-14 11:40:43,702 Waiting for JupyterHub to come up (20/20 tries)"
I had a lot of things running on this jupyterhub so I just started a clean fresh one and everything is working fine. So there must have been some issue with multiple other things running on the machine.

Many thanks

Tom
