### ISSUE TITLE
Issues displaying the dashboard with Safari and IE

### ISSUE THREAD

**Issue by tomnewg** [ideonate/cdsdashboards#19]
Hi all,

I have been setting up the cdsdashboard. Everything works perfectly with Chrome.
Checking the dashboard with other browser didn't work
With safari I can only see the markdowns but no widgets and with IE I get a blank white page.

Has anyone else experienced this? Any suggestions on why that is happening?

Many thanks

Tom

**Comment by danlester** [comment]
Thanks for the report. Are you talking about a specific dashboard, e.g. a Voila ipynb file? (Rather than something in the ContainDS Dashboards user interface)

Either way, please could you provide more details? If it's a Voila problem please supply a cut-down ipynb file that still exhibits the problem.

We might need to pass it on to the Voila team, but it would be good to see if we could reproduce it first. It's possible that it's specific to the way cdsdashboards is starting it (I presume you are still using the 'default' Voila template).

Thanks.

**Comment by tomnewg** [comment]
Hi Dan,

sorry I should have tested that before. It is a voila issue not cdsdashboard. 

You can close this thread.

Many thanks

Tom
