### ISSUE TITLE
Streamlit runs on a different conda environment

### ISSUE THREAD

**Issue by ricky-lim** [ideonate/cdsdashboards#24]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A dashboard creation form that could show user-specific conda environments that runs a streamlit dashboarding server.

**Describe alternatives you've considered**
Using the global conda environments, however streamlit does not run within a specified environment.
It stills runs with base python, instead of the specified python environment.

Below is the error, in which I tried to use a conda env that installed `bqplot` package.
```
File "/opt/conda/lib/python3.8/site-packages/streamlit/ScriptRunner.py", line 319, in _run_script
    exec(code, module.__dict__)
File "/home/jovyan/test_streamlit.py", line 2, in <module>
    import bqplot as bq
```

The solution, that I thought that a user could create her/his own environment, for instance with miniconda to run streamlit server.

**Background context**
I like to explore streamlit as a dashboarding framework for a project and every project has a specific set of dependencies.

**Configuration**
The setup is using zero to kubernetes.

Thanks in advance. I look forward to hearing from you.

**Comment by danlester** [comment]
Thank you for your post!

I think there are two issues here:

1. Ultimately, whether the conda env is global or per-user all comes down to the configuration of your singleuser environment - i.e. the Docker image you are using for your Jupyter server, and any conda configuration in that or in the user's home folder. I'm not sure why Streamlit isn't working as a global env anyway.

2. Making a list of global conda envs and adding to jupyterhub_config is one thing, but if individual users can create their own conda envs, how do we allow them to specify the env when creating a new dashboard? Assuming global and per-user conda envs are really very similar (it's just that per-user envs are in the home folder) then it is true that the hub admin can't just maintain a big list of everyone's conda envs. The easiest approach would be to allow user to enter the full name of a conda env when they create the dashboard - so it doesn't have to be restricted to the global list.

So I think the first question is why you're not getting global conda envs to work. They should really! And then how do we allow the user to create similar conda envs on a per-user basis.

Please note it might not be a good idea to make per-user conda envs anyway since home folders are often mounted using slower media. It's possible that Kubernetes isn't the best solution for your JupyterHub - I'm happy to discuss.

What single user image are you using, and how are you attempting to create a new global conda env (if you have tried that yet)? e.g. do you have a Dockerfile extending one of the existing images, with an attempt to add new conda envs on top?

I've tried to play around with adding extra conda envs on top of the [example image](https://github.com/ideonate/cdsdashboards/tree/master/docker-images/singleuser-example), including `RUN conda init bash
` but I haven't been able to get it to stick yet, and I see the same problem as you - packages don't seem to be found.

So far I'm seeing the familiar issues that `source activate` works but `conda activate` doesn't seem to.

**Comment by danlester** [comment]
To get a global conda env, this has worked for me by adding to the example [Dockerfile](https://github.com/ideonate/cdsdashboards/tree/master/docker-images/singleuser-example):

```
USER $NB_UID
RUN conda create --name globalenv1 -y
RUN source activate globalenv1
RUN conda install -c conda-forge bqplot -y
```

And of course add to config.yaml:
```
    conda-conf: |
      c.CDSDashboardsConfig.conda_envs = ['globalenv1']
```

If you've also been trying to get a global conda env working first, hopefully this helps - please let me know.

If you haven't really been looking into Dockerfiles at all, and are just hoping to get a local conda env installed in the home folder, that's fine we can start from there! Just let me know more about the config of your singleuser servers, e.g. at least the Docker image you are using.

**Comment by ricky-lim** [comment]
Hello,

Thank you very much for your swift response and a helpful guidance.

Yes, I could confirm that the global conda env, now works with my setup, after following your guidance. 

The way I organized the global environment is via `environment.yml` file within a folder `conda-env` then I just added these lines to the `singleuser` Dockerfile:

```
COPY conda-env conda-env
USER root
RUN fix-permissions conda-env
USER $NB_UID

# Create custom environment...
RUN conda env create -f conda-env/test-env.yml
```

I agree that user-specific envs might not be a good idea for maintenance on the production cluster. However for our non-production environments, a flexibility to choose an environment to run the dashboard would still be very useful.

**"The easiest approach would be to allow user to enter the full name of a conda env when they create the dashboard - so it doesn't have to be restricted to the global list."**

Would it be a good idea, to allow users specify an **absolute path** for the conda-env, instead of a just a name?

Thank you again for your helpful guidance.

Cheers

**Comment by ricky-lim** [comment]
I was wondering if you know a workaround to run a streamlit script with the interpreter specified with a shebang, for instance in this script, to run using `/opt/conda/envs/test-env/bin/python`
```python
#!/opt/conda/envs/test-env/bin/python

import streamlit as st
import pyjokes
import sys


st.write(sys.version)

if st.button('Make me laugh'):
    result = pyjokes.get_joke()
    st.write(f'{result}')
```

Thanks in advance.

**Comment by danlester** [comment]
Thank you for your update. Great to hear that at least global conda envs work - your Dockerfile snippet is really helpful.

I would like to get the local conda envs working too.

Ideally, it would be possible to specify either the full path or just a name (which should be fine if things are set up to locate it by name easily). As far as I know, it might already possible to set paths or names in the global list of conda envs anyway while we are experimenting. And then a UI change would mean the user can just type any name or path when they've created their own conda envs locally.

There was something slightly off with the conda installation in the singleuser images, so this still needs some work. I hope to try again soon, and please let me know if you also make any progress.

I haven't tried the shebang approach yet.

**Comment by danlester** [comment]
OK I think I've got somewhere...

Add to singleuser Dockerfile (within a USER $NB_USER section towards the end):

```
RUN conda init bash
COPY .condarc /home/jovyan/.conda/
```
where .condarc contains:

```
envs_dirs:
  - /home/jovyan/.conda/envs
```

Then in a terminal window within a Jupyter server I run:

```
conda create --name env2 -y
conda activate env2
```

This seems to work, and I can e.g.
```
conda install -c conda-forge pyjokes
```

However, note that I also seem to need to install Streamlit directly into this conda env too:
```
pip install streamlit
```

At that point, as long as I have 'env2' listed in the JupyterHub config:
```
c.CDSDashboardsConfig.conda_envs = ['env2']
```
and select that for my dashboard, the dashboard works fine...

As before, the next step would be a way for the dashboard developer to be able to type their own local conda env names (or maybe paths) because it's not really a global conda env available to everyone.

But first, I wondered if this works for you so far? The conda env is stored within the user's home folder.

**Comment by ricky-lim** [comment]
Hi Dan,

Thank you for setting up the test and your useful guidance.

I tried with `python -m pip install pyjokes` from a local-env and as you mentioned I also observed such leaking across environments. Furthermore, within `base` environment, I could also `import pyjokes`, unfortunately.
If I do a pure, conda-way, with `conda install -c conda-forge pyjokes`, the leaking is not observed. 
conda and pip appears to work together, unfortunately with a few unxpected suprises.

Following your instructions, I could confirm that the current conda-setup works as well for local envs with streamlit.

With relation to the singleuser docker image, I have a question regarding how could streamlit uses the authenticated state of a user ?
Within the singleuser image, the `NB_USER` env is set into jovyan and `JUPYTERHUB_USER` is set to the creator of the dashboard, instead of the authenticated user.
I was wondering what is your advice for a dashboard creator to use the authenticated state, such as a username following the dashboard authentication?

Thank you in advance for your time and kind guidance. 

I look forward to hearing from you.

Cheers

**Comment by danlester** [comment]
Great, so I think the conclusion is that it should be possible to make use of the feature we've been talking about - allowing the dashboard creator to type the name of any local (or global) conda env or path. I've separated this into a new feature request: #27 

Regarding your other question (which is a great question), I've also set up a new feature request: #28 

Actually, if you have any further background to add to that issue, please do - e.g. some idea of why you want the user's JupyterHub username in your dashboard and what you would do with it.
