### ISSUE TITLE
Open dashboard automatically

### ISSUE THREAD

**Issue by fcollonval** [ideonate/cdsdashboards#33]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

It would be nice to switch to the dashboard once the server is started instead of requesting the user to click on "Go to dashboard" button.
This will be similar to the behavior of the notebook/jupyterlab server.

**Describe alternatives you've considered**
N/A

**Background context**
N/A

**Configuration**
N/A

**Comment by danlester** [comment]
I think this now makes sense, good suggestion.

It is important to have the dashboard view url as the main link to give to users in case the dashboard server is down. If they linked straight to the dashboard server, it would try to spawn the user's own named server if the dashboard server is not running. So the dashboard view URL is important to co-ordinate dashboard restarting, but could certainly redirect automatically when ready.

**Comment by danlester** [comment]
This is now available in 0.3.4. I think part of the original inspiration for the 'Go To Dashboard' button to open in a new tab was because there is no direct way to get from the actual dashboard back to the hub. The Jupyter notebook interface has a 'Control Panel' button; JupyterLab is missing such a link.

So I have made the links from the dashboard list open in a new tab instead, to the 'dashboard start' page which automatically redirects once ready. When creating/saving a dashboard, the POST operation remains on the same page, so in that case there is no new tab.

There is nowhere displaying the dashboard description any more, so I have added these as tooltips ('title' attribute) to the links in the list of other users' dashboards.

Anyway please take a look when you get a chance and let me know what you think.

**Comment by fcollonval** [comment]
Thanks a lot @danlester for the promptness of addressing this.

> JupyterLab is missing such a link

Actually there is a entry in the `File` menu when you are using JupyterHub that open the Hub Control Panel (it is also available as command).

**Comment by danlester** [comment]
Thanks for pointing that out about the link to Hub in JupyterLab!
