### ISSUE TITLE
Removing Named Server functionality not working as described

### ISSUE THREAD

**Issue by parodayco** [ideonate/cdsdashboards#45]
**Describe the bug**
Adding the following to my cdsdashboards_config.py and reloading per the [Hub Options: Named Server display documentation](https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/huboptions.html#named-server-display) does not work.
```
c.JupyterHub.template_vars = {
    'cds_hide_user_named_servers': True,
    'cds_hide_user_dashboard_servers': True
    }
```

**To Reproduce**
`nano /opt/tljh/config/jupyterhub_config.d/cdsdashboards_config.py`
add code above and save
`sudo tljh-config reload`
...and log back in as regular user. I expect the New Dashboard option to be hidden but instead I see the following:

**Screenshots**
<img width="705" alt="image" src="https://user-images.githubusercontent.com/42258137/97214219-2437bd80-1799-11eb-8fe5-48b5ad941938.png">

**Configuration**
see above

p.s. Thank you so much for creating this addition to Jupyterhub, it's wonderful!

**Comment by danlester** [comment]
Thank you for your issue - I'm pleased to hear you like the extension!

Sorry for any confusion, but I think it is possible that those settings are working as I intended... they should affect what the user sees on their home page (/hub/home) and not on the Dashboards page (/hub/dashboards).

![image](https://user-images.githubusercontent.com/786238/97278193-5dbc0780-1831-11eb-8493-a5b6d4ebe35d.png)

Beneath the two big buttons at the top:

cds_hide_user_named_servers=True would hide the Named Servers section.
cds_hide_user_dashboard_servers=True would hide the Dashboard Servers section.

I imagine you are hoping to create users who are only present to view dashboards (e.g. non-technical users) and who you don't want to create dashboards or servers. I think that's really important. There is some work already carried out to make this possible, and I hope to be able to work on it over the next few weeks. The issue is https://github.com/ideonate/cdsdashboards/issues/37
