### ISSUE TITLE
Please support running Panel apps via python command

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ideonate/cdsdashboards#7]
Sometimes if you have a more advanced use case you don't start your Panel app via `panel serve`.

Instead you start it via `python app.py` and the `panel.serve` command inside the file. The name `app.py` is just an example. It can be the name of any python file. You can find the `serve` documentation [here](https://panel.holoviz.org/api/panel.io.html#panel.io.server.serve).

An example is the `app.py` file for awesome-panel.org at https://github.com/MarcSkovMadsen/awesome-panel/blob/master/app.py.

**Please support this use case as well.** Thanks.

#### Simple Example `app.py` file.

```python
import panel as pn

def app1():
    return pn.pane.Markdown("# Hello Panel World")

def app2():
    return pn.pane.Markdown("# Hello ContainDS Dashboard World")

ROUTES = {
    "panel-app": app1, "cdsdashboard-app": app2
}

pn.config.sizing_mode="stretch_width"
pn.serve(ROUTES, port=80, title="Example")
```

```bash
python app.py'
```

![image](https://user-images.githubusercontent.com/42288570/84560184-ad49dd00-ad41-11ea-82d9-f4956f743b56.png)

**Comment by danlester** [comment]
@MarcSkovMadsen This makes sense, and I would like to support it.

The example would definitely need a way for the required port number to be passed through, e.g. by taking a command-line parameter. JupyterHub needs to decide on a port that doesn't conflict with any other running servers.

If a particular approach was very common in the Bokeh/Panel world then it might make sense to support it directly, but in any case, I think an important feature for ContainDS Dashboards is for the JupyterHub admin to be able to set bespoke deployment patterns.

This should be simple enough for the admin, and I will be sure to make a minimally working version of your example to show how it can be added.

Thanks for the report!

**Comment by danlester** [comment]
cdsdashboards 0.0.19 release allows you to specify your own custom presentation types (using a configuration called a 'launcher').

In the [custom launchers docs](https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/customlaunchers.html) I use a modified version of your example script showing how you might accept port and host origin parameters so that it can also run behind a reverse proxy (which is what JupyterHub and cdsdashboards need it to do of course).

However, in Panel or Bokeh there appears to be some configuration missing that really needs to be there for the index page to work correctly. My docs show a hack that gets round this (basically, they just need to use relative URLs or also allow a prefix on the user side but not the server side). Maybe I'm missing the configuration needed, but otherwise it would be helpful if I raise an issue on the Panel/Bokeh projects.

An alternative would just be to write your own 'index' app to serve at the '/' route.

The point is that the user accesses the panel sub-app at e.g.:
http://myjupyterhub.net/user/dan/dash-custom-panel/app1

If I provide prefix=/user/dan/dash-custom-panel to the Panel server then the index page shows the correct URL - but if I click on it then it doesn't serve the app because the Panel server also adds the prefix to the route. That is, the app is actually being served through the URL /user/dan/dash-custom-panel/user/dan/dash-custom-panel/app1 by the time it's passed through the reverse proxies.

Voila, for example, allows you to specify two different 'prefixes' on the command line:

```
voila file.ipynb --Voila.base_url=/user/dan/dash-custom-panel/ --Voila.server_url=/
```

This means that its internal route is at the root (/) but that it should output any user-facing URLs with the base_url prefix.

Anyway, the custom launcher feature should be seen as experimental, but it can accommodate your example use case! Please let me know how you get on.

Thank you for helping form this functionality. As a side effect, it also allows customization of the builtin launchers to suit your environment.

BTW if you are using DockerSpawner the approach is different - it's just up to you to make your own custom entrypoint shell script.

Dan

**Comment by danlester** [comment]
I have posted about this issue on Panel's discourse site: https://discourse.holoviz.org/t/panels-default-index-html-causes-prefix-confusion-behind-reverse-proxy/850
