### ISSUE TITLE
Split requirements between `install_requires` and `extras`

### ISSUE THREAD

**Issue by fcollonval** [ideonate/cdsdashboards#9]
**Describe the bug**

When installing, pip download all dependencies even those not mandatory (i.e. depending on the spawner):

```
Installing collected packages: Click, bokeh-root-cmd, pluggy, multidict, yarl, async-timeout, aiohttp, simpervisor, jhsingle-native-proxy, rshiny-server-cmd, pygments, jupyterlab-pygments, pyzmq, jupyter-core, jupyter-client, Send2Trash, pyparsing, packaging, webencodings, bleach, testpath, defusedxml, pandocfilters, nbformat, mistune, nbconvert, wcwidth, prompt-toolkit, parso, jedi, pickleshare, backcall, ptyprocess, pexpect, ipython, ipykernel, terminado, jupyter-server, voila, voila-materialstream, plotlydash-tornado-cmd, websocket-client, docker, escapism, dockerspawner, cdsdashboards
```

It would be better to use the [extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras) section in setup.

**To Reproduce**

`pip install cdsdashboards`

**Configuration**

N/A

**Comment by danlester** [comment]
Thank you for creating this issue.

It's something I said that I should do in the docs... it's time I did it!

I think the project has matured enough that the different sets of dependencies can be clearly identified and described.

Dan

**Comment by danlester** [comment]
The plan is to remove the docker dependencies completely. As with the other environments (k8s etc), it just needs to be assumed that the JupyterHub already has things like DockerSpawner if needed. Having said that, cdsdashboards when using dockerspawner does use the docker package. That's currently a dependency of dockerspawner anyway, but it's not guaranteed. So maybe that would need to be made an 'extra' dependency e.g. [hub-docker] in the future. It's very unlikely that dockerspawner would stop needing docker anyway!

Beyond that, the default cdsdashboards install will no longer install jhsingle-native-proxy or voila etc.

There will be a [user] extras option that does install jhsingle-native-proxy (plus the minor wrapper scripts such as plotlydash-tornado-cmd, rshiny-server-cmd, and rshiny-server-cmd which are minimal). For now it will also install the main cdsdashboards and its dependencies too - most of those would find their way into e.g. a singleuser docker image anyway since those typically require the jupyterhub package and the deps are similar. It might still install voila, but if so with another extras option that doesn't. Something like that.

Anyway, thanks again for bringing this up. Hopefully this proposal is a step in the right direction. Code is in master branch if you do want to take a look.

**Comment by fcollonval** [comment]
Awesome thanks for the reactivity.
